sudo: required
language: python
services:
- docker
before_install:
- echo "$TRAVIS_COMMIT"
script:
- docker build -t "$DOCKER_USER/memcock" .
- docker tag "$DOCKER_USER/memcock:latest" "$DOCKER_USER/memcock:$(echo $TRAVIS_COMMIT| cut -c-10)"
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push "$DOCKER_USER/memcock"
before_deploy:
- openssl aes-256-cbc -K $encrypted_9ad22a92b11d_key -iv $encrypted_9ad22a92b11d_iv -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
 provider: script
 skip_cleanup: true
 script: ssh -o StrictHostKeyChecking=no admin@memcock.tk "./deploy.sh memcock $(echo $TRAVIS_COMMIT| cut -c-10)"
 on:
   branch: master
env:
  global:
  - secure: k2ebwBIjfeuwtcAk1MzHDF5eI/B6vxmhJgMNmIHqRTvIfm1leovC7lb2e/38mf+V8gTXXI1V0a3X/Ycv34zRRI6lo6ghdSRtP/BQRqN83Kae+Cn0fGzIhQJNfHufXAaOOw5aElJyvxVhZFZouQlbB3bF7pnExLYJHgS3bk6zUwr8I8eOqnTCDP/JEL5DGPD6lLxn1nWeiTGoqZcb6g/BK8tT7Psj/wdcQWbYqY90Pz9oMMwcHkw7y0vGZjvOBsxUpOlLO0mZ/p+sxQgYMJyGJvFoYqw3GMGWmGhztwbs22r9ww/Y5vcQ80HB9a+l1POEcn5YPUrwyaiavITdmBN41OP867pirDS1sMDfoOUz81j7aT1+hOsfRwFIEq5h4FvfR9NfLHoJ4RdidLDozcpIUTxpCIU0lUs+xWpmr4JQayvYzFrZ/HAAUjgBD6shO2LX7adY43Xa4lH3vb/lT3+UNeByAxL2lZfuTsnBo1bM7qb7mIlmaamgmuHM+eLMJ7ZTKgQa87RwJzgz9vZBElkjMLiXVWPlj/fZ9w4cUhdzk5O3UEe5hQTioJ+answH6AJQDr7DWPObN2EUQAdUbpAvEN0MIvx7O3vNt0v8S6peKKkhfv4DLqT4LnSs4pGDU1cGk6GZYdv/qPys+UvlzkrR7WB+uNVMDuWOj//nk5O8jok=
  - secure: XcULfnhrvpqqXLC63FlEHDuwoUr3IVnI8451nlE7vGgGoUhmeWBNs6itsJ1edhQ6YkW6jnSRCzjkvZRIROuhXICDwimfDnFaAujXwlgFEJhIZOAsaYBp1JmYL37QVsDvYPmlZqlPuKH4qpWghH8dZBjPbKsQA2VG+99+vg5RlV/IM4E0rDchsrW8A9o5HPSAxyzjEJNZ9xOAlmLdviepvXMe5/qHcnmkntHiZusZdaEaxV2sK/Q6ofWC3ouZw/JvtIU9DttaAI4P83C9ANmPEcyR82TKppvyhSmNuo4/nxKZAaJjAGrRKqWW6u05HIYZvsJYOKvL5euTOV/AM83JfDxTARKd4xl8KUyO4KnpwCRlHd/dmNg5bGhb966VqAJ/UHvhhV35dCqavt7lMwPkUl790q63vTeLBIZZWx19JvXHyo5b+cs2WQiEUgeYYdkI9zW+sdSagMm06Bv9h84LT9Tj8j8o8Xy2KR+gGrEN+MR9CQPb65ICEEonR5F83957RX5l/NvHsQvp+IwB7aftf2ig/P63RSt/Tne4bMb884cd3mLTTt3ARacM09dGzMOBrq8RLK5sfqXYfPtT1giuZkR53BPUlO0LTQBBmFpf3gP1x7jEYNwH1FoZ0nYBNf1T9K9vRu726IONtaN7rHVqfDw2sD4tdr1VsodscwHUTWY=
